import{a as _,S as q,i as c}from"./assets/vendor-CxL-4rjn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const w="42906577-f3a74609592fdc176ad4717b8",B="https://pixabay.com/api/";async function f(o,t){const a={key:w,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await _.get(B,{params:a})).data}const m=document.querySelector(".gallery"),M=new q(".gallery a"),y=document.querySelector(".load-more"),h=document.querySelector(".loader");function p(o){const t=o.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:i,comments:S,downloads:v})=>`
    <li class="gallery__item">
    <a href="${s}" class="gallery__link">
        <img src="${a}" alt="${e}" loading="lazy" class="gallery__image" />
    </a>
    <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${i}</p>
        <p><b>Comments:</b> ${S}</p>
        <p><b>Downloads:</b> ${v}</p>
    </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",t),M.refresh()}function $(){m.innerHTML=""}function g(){h.classList.remove("loader-hidden")}function L(){h.classList.add("loader-hidden")}function b(){y.classList.remove("hidden")}function d(){y.classList.add("hidden")}const O=document.querySelector(".form"),x=document.querySelector("input[name='search-text']"),E=document.querySelector(".load-more");let l="",n=1,u=0;O.addEventListener("submit",H);E.addEventListener("click",P);async function H(o){if(o.preventDefault(),l=x.value.trim(),!l){c.error({message:"Search field cannot be empty!"});return}n=1,$(),d(),g();try{const t=await f(l,n);if(u=t.totalHits,t.hits.length===0){c.info({message:"No images found. Try another query."});return}p(t.hits),n*15<u&&b()}catch{c.error({message:"Fetch error. Try again later."})}finally{L()}}async function P(){n++,g(),d();try{const o=await f(l,n);if(p(o.hits),T(),n*15>=u){c.info({message:"We're sorry, but you've reached the end of search results."}),d();return}b()}catch{c.error({message:"Failed to load more images."})}finally{L()}}function T(){const o=document.querySelector(".gallery__item");if(!o)return;const t=o.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
